# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fdc4ea385669a4159189bfb5210c19d293cc4ca4ffc7cd965f4ce0f2212b3ef3aa58db0ca7e373071c58d31b94b31c69c15a194c14a5c720d2fecbc8b95f97a

test:
  secret_key_base: ae83a37f2e82d66ad0e559a1e7a5f5fdc810f4814f686253532c5dda2c3df4e590b0936b2bfe1276c03e1f0f43dabe4749a166400ef0a5433fd2eaccb9813fc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
